[[parts]]
id = 'pico'
name = 'Pico'
desc = 'A tiny disposable probe. Carries sensors and not much else. Use it to scout bodies for resources.'
dry_mass_kg = 12.0
energy_kwh = 1800.0
inputs = {metal = 2}
ports = 0 # no ports, disposable

[parts.fuel]
max_fuel_mass_kg = 8.0
isp = 450.0
thrust_kn = 0.05


[[parts]]
id = 'dray'
name = 'Dray'
desc = 'Can land on bodies, mine resources like water ice and Ilmenite, and bring them back to the station for processing.'
dry_mass_kg = 500.0
energy_kwh = 7#200.0
#inputs = {metal = 4}
ports = 1

[parts.fuel]
max_fuel_mass_kg = 875.0
isp = 450.0
thrust_kn = 1.0

[[parts.modules]]
kind = "store"
resource = "energy"
amount = 5_000_000.0
capacity = 5_000_000.0

[[parts.modules]]
kind = "store"
resource = "water"
capacity = 500.0

[[parts.modules]]
kind = "miner"
kg_per_s = 0.0015
power_watts = 5.0
